# This is meant for development purposes only. If 'true',
# Aabernathy will output more data to internal logging
# and server console. Optional values are 0-3
debugLevel: 0

# Messages defined here map out things that will be sent
# either to one, some or all players active in the game.
# Whenever an event is triggered, onPlayerJoin for example,
# a message will be chosen at random to send to all players.
messages:

  # Message of the Day will slightly differ from the above.
  # Instead, each line from the list will be output to the
  # joining player's console.
  motd:
    - '&fHello %(player), welcome to Aabernathy!'
    - '&fDid you know the server has multiple ways to connect'
    - '&fwith other players of the community?? Click on the'
    - '&fbelow to see all that Aabernathy has to offer:'
    - '&9DISCORD&7: &fhttps://discord.gg/G5mtAd8a8a'
    - '&9BLUEMAP&7: &fhttps://mine.aabernathy-mc.app/minecraft/'

  # Line items added to this section will be chosen at random
  # to send to all players.
  onPlayerJoin:
    - '&a%(player) &fhas entered the chat!'
    - '&a%(player) &fhas appeared from out of nowhere!'
    - '&a%(player) &fmaterialized from out of nowhere!'
    - '&a%(player) &fsuddenly exists, just as they always have.'
    - '&fA wild &a%(player) &fappears!'
    - '&fAppearing from the void &a%(player) &fmakes an entrance!'

  # Line items added to this section will be chosen at random
  # to send to all players.
  onPlayerQuit:
    - '&c%(player) &fhas left the chat!'
    - '&c%(player) &fvanished into thin air...'
    - '&fAnd like that &c%(player) &fno longer exists.'
    - '&fLight momentarily bends around the spot &c%(player) &fonce stood. The disappear without a trace!'
