# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build&Deploy - Test

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.MINECRAFTD_SSH_PRIVATE_KEY }}
        known_hosts: '<placeholder>'

    - name: Install Known Hosts
      run: ssh-keyscan -H ${{ secrets.MINECRAFTD_HOST }} >> ~/.ssh/known_hosts

    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'

    - name: Pre-Build with Gradle
      run: chmod +x ./gradlew; find scripts -type f | xargs chmod +x

    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    - name: Deploy Build to Remote
      run: scripts/deploy-build.sh
      env:
        MCSERVER_ENVIRON: test
        MINECRAFTD_HOST: ${{ secrets.MINECRAFTD_HOST }}
        MINECRAFTD_USER: ${{ secrets.MINECRAFTD_USER }}
        MCRCON_PASS: ${{ secrets.MINECRAFTD_MCRCON_PASS }}
        MCRCON_PORT: 25576
